Added Discord Invites to README
Slimefun-Addon-Community/Community-Center pull request #12
Opened 2021-01-23 14:42 UTC by TheBusyBiscuit

I added our two discord servers to the README

2021-01-23 15:29 UTC, Seggan requested changes

2021-01-23 15:29 UTC, Seggan commented on README.md
> +The Slimefun Addon Community also has it's own discord server for any of our projects too!
its not it's

2021-01-23 17:35 UTC, Seggan approved these changes

2021-01-25 15:31 UTC, WalshyDev approved these changes
LGTM

2021-01-25 15:34 UTC, merged